### ISSUE TITLE
Could you help, audio-modul...

### ISSUE THREAD

**Issue by MacDos** [DeadEnded/MotionEyeAudio#2]
Sorry, I'm New. I would like to use:
"ReSpeaker 2-Mic Pi HAT V1.0 for Raspberry Pi Zero and Zero W, Raspberry Pi B+, Raspberry Pi 2B and 3B" 
for MotionEyeAudio, is it easy possible?
I found on Youtube "Raspberry Pi Zero W Surveillance Camera" from "ExplainingComputers" that looks easy to use, but without audio, can you help me?

**Comment by DeadEnded** [comment]
If you have a camera that supports audio and is setup in MotionEye already, just copy the script to the correct folder, then add the two parts explained in the readme.  That should do it, but since this hasn't been tested on more the 2 or 3 setups, it could require some tweaking.  YMMV

**Comment by walthowd** [comment]
Yes, this should be possible.You'd have to modify the script to have ffmpeg record from your Pi Hat instead of the stream, but as long as you put it into a compatible format it should all work.

https://trac.ffmpeg.org/wiki/Capture/ALSA#Recordaudiofromyourmicrophone

**Comment by DeadEnded** [comment]
Ah okay, I understand... I don't know that hardware so wasn't aware it had separate devices.
You would change line 13:
```
 full_stream="$(echo ${stream} | sed -e "s/\/\//\/\/${credentials}@/")"
```
Replace everything after the `=` with your stream path and I believe should work as walt said.

**Comment by DeadEnded** [comment]
It has been over 3 weeks - is no news good news 😄 
If you have solved this please close the issue.
If there is no response I will assume it is fixed and close the issue.

Thanks!
