### ISSUE TITLE
Not working, is project dead?

### ISSUE THREAD

**Issue by codywarmbo** [DeadEnded/MotionEyeAudio#8]
I've followed instructions closely, using an Ubuntu 20.04 VM, and am having no luck with this. When I try to run it manually I get 'No such file or directory'.

**Comment by DeadEnded** [comment]
I am no longer using this script, but I see no reason it shouldn't work.
If you can post your config someone might be able to identify the error.

FYI this works for MotionEye Container - but sometimes not for MotionEyeOS without further modifications.

**Comment by DeadEnded** [comment]
Have you figured out your issue?
If not, you can share some details on your installation method and configuration setup.
You said you installed it on a VM - this script was written using the docker image.
So, if you don't have the same directory pathing, you may need to adjust some of them.

Cheers!
DeadEnd

**Comment by codywarmbo** [comment]
Sorry for not closing this. I tried this via the docker image in an Ubuntu VM is what I meant to say. I moved on to a different solution but I believe my problem was indeed permissions based.
